### ISSUE TITLE
perl file not working

### ISSUE THREAD

**Issue by maxybck** [junchaoshi/sports1.1#10]
whenever I run the perl script sports.pl I get the same issue. What is going on?

![image](https://user-images.githubusercontent.com/57376252/98874931-6d923900-2438-11eb-8f6d-0b014c4c1a7a.png)

**Comment by junchaoshi** [comment]
Hi,

It seems Perl cannot get the absolute path of your file test.txt, maybe you can try to input it manually.

**Comment by maxybck** [comment]
No that is not the issue:
![image](https://user-images.githubusercontent.com/57376252/99320001-d9551700-2827-11eb-81d8-e6df2404a83d.png)

**Comment by junchaoshi** [comment]
Could you print the head of your test.txt file?

**Comment by junchaoshi** [comment]
You can try to input a single .fa/.fastq file first to test the script.

**Comment by maxybck** [comment]
hello, you got me it was user error. I left the /home out of the absolute path. If you don't mind, can you confirm the format of the input files, do they need to be unzipped fastq files?

**Comment by junchaoshi** [comment]
Yes, the compressed files need to be unpacked.

**Comment by maxybck** [comment]
also it needs to be called <name>.fastq correct? my files were fastq format but called <name>.fastqsanger and that did not work

**Comment by junchaoshi** [comment]
Yes, suffix with .fastq/.fq is needed in your case.
