### ISSUE TITLE
CCA end annotation

### ISSUE THREAD

**Issue by xiaoyunguo** [junchaoshi/sports1.1#14]
Hi,
 Thank you so much for answering my previous questions promptly. 
I have another question about the CCA end annotation: does it only count reads with intact non-template CCA tails or count those with non-template C or CC tails as well? I couldn't tell from my result because I see only intact CCA tails.
 Thank you very much!

**Comment by junchaoshi** [comment]
Only those tsRNAs with the entire CCA end will be annotated as tsRNA-CCA-end.
