### ISSUE TITLE
Overlapping between different annotation?

### ISSUE THREAD

**Issue by xiaoyunguo** [junchaoshi/sports1.1#15]
Hi,

 Thank you so much for prompt reply to my previous questions. Really appreciate it. 
 I have more questions about interpreting the output from sports: 

- Is there overlapping between different classes? for example in output xxx.summary.txt, I saw the following classes for tRNA. Are reads counted in tRNA_5_end (and other ends) also counted in the tRNA_Match_Genome class? 

- The output pdf files shows the percentage of each type of tRNA in a pie chart, how the tRNA percentage is calculated? (5-end, 3-end, and CCA-end divided by the tRNA_match_genome plus tRNA_unmatch_genome? are mitotRNA also included in the calculation?

Thank you so much for your help!

--------- following is the classes in the summary.txt file in my case---

 GtRNAdb-mature-tRNA_Match_Genome
GtRNAdb-mature-tRNA_5_end_Match_Genome
GtRNAdb-mature-tRNA_3_end_Match_Genome
GtRNAdb-mature-tRNA_CCA_end_Match_Genome
GtRNAdb-mature-tRNA_Unmatch_Genome
GtRNAdb-mature-tRNA_CCA_end_Unmatch_Genome
mitotRNAdb-mature-mt_tRNA_Match_Genome
mitotRNAdb-mature-mt_tRNA_3_end_Match_Genome
mitotRNAdb-mature-mt_tRNA_CCA_end_Match_Genome
mitotRNAdb-mature-mt_tRNA_Unmatch_Genome
mitotRNAdb-mature-mt_tRNA_CCA_end_Unmatch_Genome

**Comment by junchaoshi** [comment]
_Is there overlapping between different classes? for example in output xxx.summary.txt, I saw the following classes for tRNA. Are reads counted in tRNA_5_end (and other ends) also counted in the tRNA_Match_Genome class?_
**Yes.**

_The output pdf files shows the percentage of each type of tRNA in a pie chart, how the tRNA percentage is calculated? (5-end, 3-end, and CCA-end divided by the tRNA_match_genome plus tRNA_unmatch_genome? are mitotRNA also included in the calculation?_
Yes, the percentage of each subtype of tsRNAs is based on all kinds of tsRNAs, including genome matched and genome unmatched.
