### ISSUE TITLE
tRNA annotation

### ISSUE THREAD

**Issue by xiaoyunguo** [junchaoshi/sports1.1#16]
Hi, 
Thanks so much for answering my previous questions. 
Another question regarding tRNA annotation. What's the criteria for annotating a read as a 3' or 5' end tRNA? 

Thanks

**Comment by junchaoshi** [comment]
As stated in the paper, the tsRNA annotation related to the tRNA loci where they are derived from (5’ terminus, 3’ terminus, 3’CCA end, etc.). The mapping criteria is based on the mismatch number the users selected.
