### ISSUE TITLE
tsRNA annotation results

### ISSUE THREAD

**Issue by daixiaozhuan** [junchaoshi/sports1.1#17]
Hi,
Thanks for your wonderful work. It's very convenient to use sports1.1 to annotate smallRNAseq data. Once I got the results, I have a questions here:

1. For tsRNA results, I saw three types: *_5_end, *_3_end and *_CCA_end, what's the difference between 3_end and CCA_end?

2.  Also, some tRNAs don't belongs to these three types, for example "tRNA-Val-AAC", which catergorize to none of these three; So how should I deal with this situation if I wanna analysis tsRNAs in my samples? 

Looking forward for your reply!
Thanks,
Xiaozhuan

**Comment by junchaoshi** [comment]
Hi Xiaozhuan,

1. The seqs annotated as *_CCA_end indicate they contain the CCA tail of mature tRNAs while those annotated as *_3_end indicate they are from the 3' end of tRNA without CCA end. 
2. Those seqs annotated as tRNA without *_end information indicate they may from the middle region of tRNAs. 
Hope the information helps.

My best,
Junchao

**Comment by daixiaozhuan** [comment]
Hi Junchao,

Thanks for your quick reply that's really helpful.

I wanna make sure the 3' end without CCA end means from the precursor tRNA? 
How do you determine 5' end or 3'end? I mean which is the exact breakpoint or position to classify them to 5' end and 3' end or internal tsRNAs?

Best,
Xiaozhuan

**Comment by junchaoshi** [comment]
Hi Xiaozhuan,

Hope the example below helps:

pre tRNA seq:
**GGGGGTATAGCTCAGGGGTAGAGC**ATTTGACTGCAGATCAAGAGGTCCCTGG**TTCAAATCCGGGTGCCCCCT**

mature tRNA seq:
**GGGGGTATAGCTCAGGGGTAGAGC**ATTTGACTGCAGATCAAGAGGTCCCTGG**TTCAAATCCGGGTGCCCCCT CCA** 

5 end tsRNA:
**GGGGGTATAGCTCAGGGGTAGAGC** 

3 end tsRNA:  **TTCAAATCCGGGTGCCCCCT**

CCA end tsRNA: **TTCAAATCCGGGTGCCCCCT CCA** 

other tsRNA: GGGGTATAGCTCAGGGGTAGAGCA, TGACTGCAGATCAAGAGGT, TCAAATCCGGGTGCCC

All the best,
Junchao

**Comment by daixiaozhuan** [comment]
Hi Junchao,

This example is super awesome! 

But why some tRNAs don't end with CCA? Are they precursors? Because I think all the mature tRNAs have the CCA end, right? 

one more question: if one sequence mapped to multiple tRNAs, how do you do with them in the further analysis?

best,
Xiaozhuan

**Comment by junchaoshi** [comment]
Hi Xiaozhuan,

Based on the theory, the precursor tRNAs may not have an extra CCA end, so we add an extra CCA end to pre-mature tRNA seqs to generate the mature tRNA seqs.

As stated in the paper, " read number of sequences from multiple matching loci are uniformly distributed (based on the assumption that each of these multiple sites equally expresses RNAs)". If a seq with 3 reads can match two types of tRNAs, it will contribute 1.5 reads to each type of tRNAs.

My best,
Junchao

**Comment by daixiaozhuan** [comment]
Hi Junchao,

Based on what you said, all precursor tRNAs added extra CCA end. Where can the 3' end without CCA come from? I'm a little confused about this.

For the second question, for example as bellow:
t00000001	GCATTGGTGGTTCAGTGGTAGAATTCTCGC	30	266781	Yes	mature-tRNA-Gly-GCC_5_end;mature-tRNA-Gly-CCC_5_end

So, mature-tRNA-Gly-GCC_5_end and mature-tRNA-Gly-CCC_5_end both have half of the total reads (266781/2)?

Thanks,
Xiaozhuan

**Comment by junchaoshi** [comment]
Hi Xiaozhuan,

The tsRNA is not tRNA. It could be considered that 3'end tsRNAs are mapping to the mature-tRNAs that without CCA end. One possible explanation is that the CCA end somehow dropped after the generation of such kinds of tsRNAs.

No, "read number of sequences from multiple matching loci are uniformly distributed". In this case, GCATTGGTGGTTCAGTGGTAGAATTCTCGC could map to 10 loci of tRNA-Gly-GCC and 2 loci of tRNA-Gly-CCC with 1 mismatch tolerance, so that the read number needs to be separated to 10/12*266781 and 2/12*266781.

Junchao

**Comment by junchaoshi** [comment]
Hi SergioRodLla,

In the *_length_distribution.txt file, for example, the reads in the GtRNAdb-tRNA_Match_Genome category include the reads of GtRNAdb-tRNA_5_end_Match_Genome, GtRNAdb-tRNA_3_end_Match_Genome, GtRNAdb-tRNA_CCA_end_Match_Genome, and the tsRNA reads from the tRNA middle region. I hope this information helps.

Junchao
