### ISSUE TITLE
Adding G to tRNA Histidine

### ISSUE THREAD

**Issue by dktanwar** [junchaoshi/sports1.1#20]
Hi,

I got another question about the tRNA Histidine. https://github.com/junchaoshi/sports1.1#trna_db_processingpl

You mentioned that a **G** is added to the 5' of the sequence.

If I check the sequences, a **G** is already present at the start of the sequence: http://gtrnadb.ucsc.edu/genomes/eukaryota/Mmusc10/mm10-tRNAs.fa

So, I guess, you are adding a **G** only if the sequence does not start with **G**. Is this correct?

Also, is there any reference for this?

Thank you in advance for clarifying.

**Comment by junchaoshi** [comment]
Hi Deepak,

No, a G nucleotide was added to all the 5′-end of histidine tRNAs. Please read the references: Nat Methods. 2015 Sep;12(9):879-84. doi: 10.1038/nmeth.3508; Proc Natl Acad Sci U S A. 1982 Nov;79(21):6475-9. doi: 10.1073/pnas.79.21.6475.
