### ISSUE TITLE
add new RNA type

### ISSUE THREAD

**Issue by daixiaozhuan** [junchaoshi/sports1.1#22]
Hi,
thanks for your wonderful work. But if I want to add other types of ncRNA database into sports, for example snoRNA, vault RNA etc. How can I do it?

Thanks

**Comment by junchaoshi** [comment]
Most of these small RNA types are included in the Ensembl ncRNA database. The easiest way to include a novel small RNA type database is to combine it with Ensembl or Rfam ncRNA database .fa file, please make sure the sequences are unique comparing with the database you would like to combine.
