### ISSUE TITLE
summary file

### ISSUE THREAD

**Issue by daixiaozhuan** [junchaoshi/sports1.1#25]
Hi Junchao,

I want to generate the ratio of different RNA types. Firstly, I extracted the information directly from the file "*.mapped.sorted.txt" in the "processing_report" folder. But I check the reads number is not correct. Then I checked the summary file as below, why the Match_Genome number is larger than the Clean_Reads? Do you have any advice on which file should I use the output the summary?
![企业微信截图_16397197048240](https://user-images.githubusercontent.com/78533758/146495079-b9c72afb-8abd-47c9-a46d-81d0998610e3.png)

Thanks,
Xiaozhuan

**Comment by junchaoshi** [comment]
It's not a normal result. Could you check the processing log file to see if everything works fine?

**Comment by daixiaozhuan** [comment]
Hi,

There is no error information in the log file. 
![image](https://user-images.githubusercontent.com/78533758/146705258-b6d41e3d-f6e7-4589-a73b-cdacb32162aa.png)

Is it because of the multi-mapping reads? I checked several samples, which all have the same problem.

Xiaozhuan

**Comment by daixiaozhuan** [comment]
Hi,

This is the command that I used as below:
![image](https://user-images.githubusercontent.com/78533758/146706236-51f6458a-f5f1-4bc9-9571-539210105344.png)

Xiaozhuan

**Comment by junchaoshi** [comment]
I mean the log file output during the running process. I.e., sports.pl -i input.fa -g genome -o output_folder -k > process.log

**Comment by junchaoshi** [comment]
I mean the log file in the processing_report folder since you performed the -k parameter.

**Comment by daixiaozhuan** [comment]
It only has one txt file as below:
![image](https://user-images.githubusercontent.com/78533758/146708916-e3194b3d-41c9-4efc-b762-380525347d3f.png)

**Comment by junchaoshi** [comment]
Since there are warnings in the processing file, please make sure your input files and/or the reference files are valid.

**Comment by daixiaozhuan** [comment]
I checked the input and reference. But I didn't find any error. By the way, I want to make sure that I use the result in the "processing_report" to report the ratio of different small RNA types. Is it correct?
![image](https://user-images.githubusercontent.com/78533758/147027338-7f0ece6e-afc3-4993-b6c4-a39aafe9d55f.png)

**Comment by junchaoshi** [comment]
Since there are warnings in the processing file, something should be wrong with your processing step. The ratio in the processing file represents the unique species of the total species aligned rather than the reads ratio.

**Comment by daixiaozhuan** [comment]
If I want to know the reads ratio. Then which file should I use?

**Comment by daixiaozhuan** [comment]
There are warnings because I used the reads that only can mapped to genome. So the unmapped genome part is empty.

**Comment by junchaoshi** [comment]
The reads of each type of small RNA and each sequence are in the [sample_name]_output.txt and [sample_name]_summary.txt which are in the [sample_name]_reusult folder. 
You do not need to remove genome_unmapped reads before annotation. The genome mapping information is already included in the result folder. And it may cause incorrect counting, as you asked at the beginning.

**Comment by junchaoshi** [comment]
Please read the README file carefully, the instruction of each output file is already included.
