### ISSUE TITLE
Error in running sports.pl

### ISSUE THREAD

**Issue by sr8510** [junchaoshi/sports1.1#26]
Hi,

I tried running sports with these parameters:
sports.pl -i files.txt -m /media/nsg/Data/Genome-assemblies/Rat/sports/Rattus_norvegicus/miRBase_21/miRBase_21-rno -r /media/nsg/Data/Genome-assemblies/Rat/sports/Rattus_norvegicus/rRNAdb/rat_rRNA -t /media/nsg/Data/Genome-assemblies/Rat/sports/Rattus_norvegicus/GtRNAdb/rn5-tRNAs -w /media/nsg/Data/Genome-assemblies/Rat/sports/Rattus_norvegicus/piRBase/piR_rat -f /media/nsg/Data/Genome-assemblies/Rat/sports/Rattus_norvegicus/Rfam_12.3/Rfam-12.3-rat -e /media/nsg/Data/Genome-assemblies/Rat/sports/Rattus_norvegicus/Ensembl/Rattus_norvegicus.Rnor_6.0.ncrna -g /media/nsg/Data/Genome-assemblies/Rat/sports/Rattus_norvegicus/UCSC/rn6/Sequence/BowtieIndex/genome -p 4 -o ./output

However I got this error message:
Filtering min lenth: 15
Filtering max lenth: 45
Mapping mismatch tolerance: 0
Use of uninitialized value $tmp in -d at /home/nsg/sports1.1-master/source/sports.pl line 352, <FILE_IN> line 1.
Use of uninitialized value $tmp in -f at /home/nsg/sports1.1-master/source/sports.pl line 387, <FILE_IN> line 1.
can not open '/media/nsg/Data/Sherif/Gtpbps small RNA seq/sports/output/sh_file/1_Gtpbp2.sh' at /home/nsg/sports1.1-master/source/sports.pl line 479, <FILE_IN> line 4.

Can you please help me figure out what`s the issue?
Thanks!

**Comment by junchaoshi** [comment]
It seems the format of your input seq files in your files.txt is not correct. please make sure to unzip your fastq or fasta data first and use the absolute path of files. You may also run one seq file first to test the pipeline before performing all the data in a batch.
