### ISSUE TITLE
Error in locating indexes

### ISSUE THREAD

**Issue by BIGRICEgo** [junchaoshi/sports1.1#27]
Hi Junchao,
I am using sports1.1 to analyse sRNAseq data. I installed as you told. The programs bowtie(1.2.1.1) and sports.pl seem to be functioning properly.  However, when I ran SPORT1.1 with my cleaned out data, I got “ Could not locate a Bowtie index corresponding to basename "Homo_sapiens/genome/hg38/genome" ” in the processing report.

I tried with these parameters: 
nohup time sports.pl -i test.fq -p 8 -g Homo_sapiens/genome/hg38/genome -m /Homo_sapiens/miRBase/21/miRBase_21-has -r Homo_sapiens/rRNAdb/human_rRNA -t Homo_sapiens/GtRNAdb/hg19/hg19-tRNAs -w Homo_sapiens/piRBase/piR_human -o output_test/ -k > log_test 2>&1

And I got these in log:
![1645962502](https://user-images.githubusercontent.com/93658092/155881362-59dfba42-dc4f-43ff-b793-eb17203413d3.jpg)

The processing report shows:
![1645962504(1)](https://user-images.githubusercontent.com/93658092/155881370-fdb9a866-4202-469d-82a7-029bf39f5396.jpg)

When I checked the Homo_sapiens file, I saw that indexes (.ebwt files) have been output. 
![1645963161(1)](https://user-images.githubusercontent.com/93658092/155881477-60242f18-e75c-4760-96b4-6a981ac49812.jpg)

After the issue occurred, I tried reinstalling SPORTS1.1 and the corresponding software, and also re-downloading the pre-compiled database. In addition, I used the bowtie software to directly build indexes and then ran sports.pl. But it seems that these didn't work out. The latest result is still the same problem.

I'm not sure which part is wrong? And How can I deal with this issue? Hope you answer soon.

Thanks!
Arya

**Comment by junchaoshi** [comment]
Hi Arya,

It's better to use the absolute address for the index files. 

Best,
Junchao

**Comment by BIGRICEgo** [comment]
Hi Junchao,

Thanks so much for your quick reply!
It almost works out except miRNA database. :(  I still met a question. The log tells:

Generating miRNA database bowtie index...

Error: could not open /home/huangrf/TASK2TRY/LAST_TRY/Homo_sapiens/miRBase/21/miRBase_21-has.fa
Command: bowtie-build --wrapper basic-0 -q /home/huangrf/TASK2TRY/LAST_TRY/Homo_sapiens/miRBase/21/miRBase_21-has.fa /home/huangrf/TASK2TRY/LAST_TRY/Homo_sapiens/miRBase/21/miRBase_21-has


And I have came into another trouble. When I used annotation.pl in the next step, it went wrong with:

nohup: ignoring input
Can't open '/home/huangrf/TASK2TRY/LAST_TRY/output_Con-J2_genome/.fa': No such file or directory at /home/huangrf/TASK2TRY/sports1.1-master/source/annotation.pl line 55.


Thank u in advance!
Arya

**Comment by junchaoshi** [comment]
The address of miRBase should be /foo/bar/Homo_sapiens/miRBase/21/miRBase_21-**hsa**, or "**has**"

**Comment by BIGRICEgo** [comment]
Hi Junchao,

I've got it. Thanks a lot! Your answer is greatly appreciated.

Arya
