### ISSUE TITLE
mt-tRNA annotation file

### ISSUE THREAD

**Issue by BIGRICEgo** [junchaoshi/sports1.1#30]
Hi Junchao,

I have only one small question regarding the Human precompiled database you provided. I noticed that the file hg19-mt_tRNAs.fa contains 29 sequences, but when I searched mitotRNAdb, I only found 22 results. Could you please explain why there is a discrepancy? Additionally, I'm just wondering whether you have plans to provide a precompiled database for hg38 in the future?

Thank you for your help and expertise.

Best regards,
Arya

**Comment by junchaoshi** [comment]
Hi Arya,

The 7 mt-tRNA variants in the reference file are collected from the subspecies to maximize the mapping rate. You may remove the last 7 sequences if you would like to.
And Yes, the updated precompiled database is on the schedule list.

My very best,
Junchao
