### ISSUE TITLE
Cannot get sports to work

### ISSUE THREAD

**Issue by sanhe374** [junchaoshi/sports1.1#32]
I have tried running SPORTS several times and I cannot manage to get it to run.

I tried using just one file and one genome using: 
sports.pl -i /mnt/d/covum/run1/fastq_run1_merged_sample/Merged_fastq/Sample1_merged.fastq -g /mnt/d/covum/genomes/genome/hg38/genome

However....

![bild](https://github.com/junchaoshi/sports1.1/assets/48206476/7fd50ee8-99e2-481e-8453-6fecb8971773)

**Comment by junchaoshi** [comment]
Hi,

Could you try to specify the output address using -o parameter? Maybe your input address is not writeable.

**Comment by sanhe374** [comment]
I tried that but it still gets another error and just like a previous issue, I get no alignments.

**Comment by junchaoshi** [comment]
Hi, could you please send the header lines of your input fastq file?
