### ISSUE TITLE
tsRNA annotation

### ISSUE THREAD

**Issue by maturityyuan** [junchaoshi/sports1.1#33]
Hi, thank you for you work in small RNA research , I would like to consult if the outcome from summary like tRNA_5_end and tRNA_3_end equal to the tsRNA?If equivalent ,then whether there tsRNAs have a uniform nomenclature.
Thank you for you attention.

**Comment by junchaoshi** [comment]
Hi,

The naming principle of the tsRNAs is attached. 

![~9XMAT_7O$O53VJHE}WM~`M](https://github.com/junchaoshi/sports1.1/assets/30919573/63c73fb1-6bc2-4014-bfac-211b08b8aeb1)
