### ISSUE TITLE
not mature-tRNA but pre-tRNA

### ISSUE THREAD

**Issue by maturityyuan** [junchaoshi/sports1.1#34]
Hi,  I would like to consult why the results is not contain match pre-tRNA information 
the operation is here :
sports.pl -i /etc/SRR/245out.fastq -p 4 -g /etc/SRR/UCSC/rn6/Sequence/BowtieIndex/genome -t /etc/SRR/GtRNAdb/rn5-tRNAs -M 1 -o /etc/SRR/output/
Thank you for you attention
Best wishes!

**Comment by junchaoshi** [comment]
Hi,

The current SPORTS version only annotates the tsRNAs containing the intron region from pre-tRNAs, since the pre-tRNA-header and -tail sequences are not contained in the GtRNAdb.
