### ISSUE TITLE
About new tsRNA

### ISSUE THREAD

**Issue by maturityyuan** [junchaoshi/sports1.1#35]
Hi,
if the sequence have maped to the genome and maped to the GtRNAdb,but the sequence can not find in tsRNA database like tsRbase :"http://www.tsrbase.org/",tRFdb:"http://genome.bioch.virginia.edu/trfdb/statistics.php".Can we consider it a new tsRNA?
Thank you for you attention.

Best

**Comment by junchaoshi** [comment]
Hi,

While I appreciate your interest, I would like to highlight that the current issue is not directly related to SPORTS1.1.
If you have any scientific inquiries pertaining to tsRNAs, I encourage you to reach out to either myself or other relevant experts in the field. 

However, I must note that the specific question you've raised raises concerns about the comprehensiveness of the tsRNA databases. It appears that the databases in question may not encompass the entirety of identified tsRNAs, thus potentially omitting the tsRNAs you are referring to.

Best,
Junchao
