### ISSUE TITLE
Bowtie problem

### ISSUE THREAD

**Issue by ceidashi8** [junchaoshi/sports1.1#37]
Dear shi,when i can not match to index of bowtie-build，although I  already have these index file.The error is that:

match to miRNA-match_genome
Could not locate a Bowtie index corresponding to basename "Arabidopsis_thaliana/miRBase_21/miRBase_21-ath"
Command: bowtie --wrapper basic-0 -f -v 0 -a -p 1 --fullref --norc --al /home/cuimingyang/sports-sRNA/text/1_S1_1_trimmed/S1_1_trimmed_match_miRNA_match_genome.fa --un /home/cuimingyang/sports-sRNA/text/1_S1_1_trimmed/S1_1_trimmed_unmatch_miRNA_match_genome.fa Arabidopsis_thaliana/miRBase_21/miRBase_21-ath /home/cuimingyang/sports-sRNA/text/1_S1_1_trimmed/S1_1_trimmed_match_genome.fa

**Comment by junchaoshi** [comment]
Hi,
Could you please post the entire command you used when running the SPORTS? It appears that the correct absolute or relative address for the miRBase reference was not entered. I always recommend using the absolute path of the file or folder to avoid any confusion. For instance, the absolute path could be: /home/Genome/Arabidopsis_thaliana/miRBase_21/miRBase_21-ath.

I hope this information is helpful.

Best regards,
Junchao

**Comment by ceidashi8** [comment]
Thank you,I took your advice to run the Sports successfully!



---Original---
From: ***@***.***&gt;
Date: Tue, Nov 14, 2023 11:09 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [junchaoshi/sports1.1] Bowtie problem (Issue #37)




 
Hi,
 Could you please post the entire command you used when running the SPORTS? It appears that the correct absolute or relative address for the miRBase reference was not entered. I always recommend using the absolute path of the file or folder to avoid any confusion. For instance, the absolute path could be: /home/Genome/Arabidopsis_thaliana/miRBase_21/miRBase_21-ath.
 
I hope this information is helpful.
 
Best regards,
 Junchao

**Comment by junchaoshi** [comment]
Glad
