### ISSUE TITLE
Should the file generated by tRNA_db_processing.pl be used for generating bowtie indexes?

### ISSUE THREAD

**Issue by SergioRodLla** [junchaoshi/sports1.1#38]
Hello,

Thank you for developing the tool. I used the provided Mus musculus pre-compiled databases files and I realized they are not the latest release. I want to use the updated files and for that I manually downloaded the mm39-tRNA fasta file. I then saw that you provide a script `tRNA_db_processing.pl` that adds CCA to 3'end and G to 5'end of Histidine. However, I saw that in the recommended command line you don't indicate the name of the tRNA_CCA index files, even though the bowtie index files are included in the mm10 pre-compiled database:
 
`sports.pl [...] -t /foo/bar/Mus_musculus/GtRNAdb/mm10/mm10-tRNAs`
Instead of:
`sports.pl [...] -t /foo/bar/Mus_musculus/GtRNAdb/mm10/mm10-tRNAs_CCA`

I wonder what to use with the updated files that I downloaded. Should I pass the *_CCA indexes to `sports.pl` ?

Thanks,

Sergio

**Comment by junchaoshi** [comment]
Hi Sergio,

You don't need to pass the *_CCA indexes to sports.pl, as the software will automatically detect them if they are present.

Best regards,
Junchao
