### ISSUE TITLE
Output folder

### ISSUE THREAD

**Issue by kittyBS** [junchaoshi/sports1.1#39]
Hi!
I started the analysis twice using the code below. The analysis was completed without any problems the first time. On my second try, I changed the files in seq_address.txt and ran it again, but I got the following error.
"Command: bowtie-build --wrapper basic-0 --threads 24 -q /home/yildize/sports/Mus_musculus/genome/mm10/genome.fa /home/yildize/sports/Mus_musculus/genome/mm10/genome
mv: cannot stat '/home/yildize/sports/output/sh_file/*.sh': No such file or directory
rmdir: failed to remove '/home/yildize/sports/output/sh_file': No such file or directory
rm: cannot remove '/home/yildize/sports/output/*.sh': No such file or directory"
The code I used in both analyzes is;"sports.pl -i seq_address.txt -p 24 -g /home/yildize/sports/Mus_musculus/genome/mm10/genome -m /home/yildize/sports/Mus_musculus/miRBase/21/miRBase_21-mmu -r /home/yildize/sports/Mus_musculus/rRNAdb/mouse_rRNA -t /home/yildize/sports/Mus_musculus/GtRNAdb/mm10/mm10-tRNAs -w /home/yildize/sports/Mus_musculus/piRBase/piR_mouse -f /home/yildize/sports/Mus_musculus/Rfam/12.3/Rfam-12.3-mouse -o /home/yildize/sports/untroutput/"
Thank you in advance for your time.

**Comment by junchaoshi** [comment]
Hi,

It seems there's an issue with the bowtie index building procedure. Could you check the mouse fgenome reference folder?

Junchao
