### ISSUE TITLE
Generate RNA length distribution per treatment

### ISSUE THREAD

**Issue by SergioRodLla** [junchaoshi/sports1.1#41]
Hi @junchaoshi,

I'm trying to get a figure like the one generated in `overall_RNA_length_distribution.R` showing that same histogram but instead of individual samples I want to show samples of a specific treatment. In my experiment I have 2 treatments with 4 samples each. I was wondering what could be the best approach. Since the script computes the RPM values using the counts for the plot, I was thinking about leveraging that to get the RPM values for the individual samples and computing a mean for each of the groups. Do you think this is the right approach to quantify the abundance per treatment? Or would it be better to just merge (by averaging the raw counts, for example) the respective samples and rerun the whole SPORTS pipeline?

Best regards,

**Comment by junchaoshi** [comment]
This question is not relevant to the software. The method for calculating the mean depends on how you view the samples for each treatment. Are these samples considered biological replicates? Do you believe the RNA amount in each sample is equivalent? If so, the first one might be appropriate.

You may want to read [this paper](https://www.nature.com/articles/s41556-022-00880-5) to better understand this issue.
