### ISSUE TITLE
how to add MT-tRNA sequence into GtRNAdb

### ISSUE THREAD

**Issue by sunhaifeng123** [junchaoshi/sports1.1#7]
Hi:
Thanks very much for your work, Sports1.0 is very nice and useful.
My species genome is mm10, and I think some tsRNAs are derived from tRNA. But when I add the MT-tRNA sequence into mm10-tRNAs.fa like this:
>Mus_musculus_tRNA-MTSer-TGA-1-1
GAGAAAGACATATAGGATATGAGATTGGCTTGAAACCAATTTTAGGGGGTTCGATTCCTTCCTTTCTTA
>Mus_musculus_tRNA-MTThr-TGT-1-1
GTCTTGATAGTATAAACATTACTCTGGTCTTGTAAACCTGAAATGAAGATCTTCTCTTCTCAAGACA

and then run sports.pl. The result is like:

> t00000651       TCCCTGGTGGTCTAGTGGTTAGGATTCGGC  30      2       Yes     tRNA-Glu-CTC_5_end;tRNA--_5_end
> t00000769       AAGAAAGATTGCAAGAACTG    20      2       Yes     tRNA--_5_end
> t00001268       GCATTGGTGGTTCAGTGGTAGAATTCTCGCCT        32      2       Yes     tRNA-Gly-GCC_5_end;tRNA-Gly-CCC_5_end

which is not my expectation. I dont know how to solve this problem. Can you give me some advices?

Thank you in andvance for any help!
Best wishes

Haifeng Sun
2020.01.10

**Comment by junchaoshi** [comment]
Hi Haifeng,

The tRNA annotation should follow the GtRNAdb naming system, such as: 

`>Mus_musculus_tRNA-Ala-AGC-1-1 (tRNAscan-SE ID: chr13.trna91) Ala (AGC) 72 bp Sc: 85.3 chr13:21242570-21242641 (+)`

The shortest version should be: 
`>Mus_musculus_tRNA-Ala-AGC-1-1 Ala (AGC) 72 bp`

And a new version of SPORTS will release soon which will have a better annotation on tRNA. :)

My best,
Junchao

**Comment by sunhaifeng123** [comment]
Dear Junchao,
Thank you very much! and looking forward to a better SPORTS!
Best wishes
Haifeng

**Comment by junchaoshi** [comment]
Hi Haifeng,
mt_tRNA database for mouse and human have updated and more species will update soon! Please update the software and the annotation databases as well.

My best,
Junchao
