### ISSUE TITLE
Version of reference

### ISSUE THREAD

**Issue by wulouis** [junchaoshi/sports1.1#8]
Hi Junchaoshi,

Thank you very much for creating such wonderful tool! Would it be possible to update the version  of genome, Rfam, miRBase and GtRNAdb? Besides, would it be possible to clarify the format criteria of different reference. That will be very helpful for people to apply sports to their unannotated ncRNA or new species.

Thanks again for your excellent tool!

Best,
Louis

**Comment by junchaoshi** [comment]
Hi Louis,

Its fairly easy to update the version of the annotation database (I will do an update them soon.) An instruction to use your own annotation database is updated.  Hope it helps.

My best,
Junchao

**Comment by wulouis** [comment]
Hi Junchao,

Thank you very much for your help! 

Best,
Louis
