### ISSUE TITLE
Compiling annotation database by user 

### ISSUE THREAD

**Issue by louismtwu** [junchaoshi/sports1.1#9]
Hi Junchao,

I would like to know what's different of the Rfam ncRNA db between ensemblgenomes and Rfam database in the section of "Instruction for compiling annotation database by user" ? Which one should we follow? X_rfam_ncrna.fa or X_rfam.fa? Shall we just choice one for the ncRNA from rfam db?

Download and extract the noncoding RNA sequences in .fa format from Rfam database (http://ensemblgenomes.org/) and put the file X_rfam_ncrna.fa into the defined folder address: <your_defined_address>; (optional)

Download and extract the noncoding RNA sequences belong to the species in .fa format from Rfam database (https://rfam.xfam.org/) and put the file X_rfam.fa into the defined folder address: <your_defined_address>; (optional)

Thank you for your help.

Cheers,
Louis

**Comment by junchaoshi** [comment]
It's a typo. Fixed. Thanks for figuring it out.
